// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkS2LF4eTVLS3ewcQDbI3GDbvWRUH-GkQ',
    appId: '1:284059994649:android:2ca2afa2f78ae589ad3888',
    messagingSenderId: '284059994649',
    projectId: 'fruits-hub-bccca',
    storageBucket: 'fruits-hub-bccca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnu51I1IJLRcgPeIrb89ZBBwV6Q9c_Klo',
    appId: '1:284059994649:ios:01ebde9143483285ad3888',
    messagingSenderId: '284059994649',
    projectId: 'fruits-hub-bccca',
    storageBucket: 'fruits-hub-bccca.firebasestorage.app',
    androidClientId: '284059994649-03rqv55cru1vu69lfduc46euqnskqcu1.apps.googleusercontent.com',
    iosClientId: '284059994649-9ppsi8prmvdbpp95pgecqu75gso1pgag.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );
}
